openapi: 3.0.3
info:
  title: online planning poker API
  description: |-
    online planning poker
    for scrum teams.
  contact:
    email: info@3doo.de
  version: 1.0.1
servers:
  - url: http://localhost/api
tags:
  - name: sessions
    description: Everything about sessions
paths:
  /sessions/{session_id}:
    get:
      tags:
        - sessions
      summary: get session data
      description: Give the data of a running session
      parameters:
        - name: session_id
          in: path
          description: ID of session to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: Invalid ID supplied
        '404':
          description: Session not found
components:
  schemas:
    Session:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie

